<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\Kunling.RobotClient.Core\Kunling.RobotClient.Core.csproj" />
    <Reference Include="RobotLibrarys"><HintPath>Lib\RobotLibrarys.dll</HintPath><Private>true</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>Lib\Newtonsoft.Json.dll</HintPath><Private>true</Private></Reference>
  </ItemGroup>
</Project>
